
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ai-agent-marketplace"
s3_bucket = ""
s3_prefix = "ai-agent-marketplace"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = ""
image_repositories = []
